### PR TITLE
Change button name to 'Attack' instead of 'Convert' in DuckHunter interface

### PR DESCRIPTION
**Pull request by TheNain38**
Could you please check that it works correctly (e.g. that I didn't forget anywhere to change the name).

### CODE REVIEW

**Comment by jmingov** [comment]
I will not merge untested code again.

 If you cant test dont make the pull request.

ty!

**Comment by TheNain38** [comment]
Ok, I'll take note. It was my last untested PR, others will mainly be on rewriting the parser on DuckHunter.py to have much easier to understand code.

**Comment by jmingov** [comment]
Nice @TheNain38 ^^.

**Comment by TheNain38** [comment]
I've written Java code, but it wasn't for Android, it was for computer ^^
But I have the basic knowledge to write a little code for Java on Android

**Pull request merged**
