### PR TITLE
Merge changes

### PR DESCRIPTION
**Pull request by kimocoder**
Ok... this needs to be reviewed before merging.

### CODE REVIEW

**Comment by kimocoder** [comment]
Think that's all for now.. but this MUST be reviewed before merging.

**Comment by Re4son** [comment]
Idea to ponder about while I'm testing:

Treble disabled our ability to easily  install a user apk through recovery. How about we install the nethunter-app as a system app, place the apks in a persistent directory and then install them during the initial run of nethunter when we set up everything else?

Any thoughts?

**Comment by kimocoder** [comment]
It's either that, or to use "adb install" externally which also is possible

**Comment by Re4son** [comment]
I was trying to avoid a tethered install.
Another alternative was using a magisk module but then we rely on too many different parts.

The option of "the installer moves the apks to a certain directory if Android >= 8 and the app installs every apk found in that directory during inital setup" looks like the best compromise to me.
What do you think?

**Comment by Re4son** [comment]
On another note: shall we rename the chroot from "kali-armhf" to kali-${ARCH}?
It's more for hygiene than practical application right now.
Arm64 is complete now and the installer is actually using a proper arm64 chroot in the latest release so we may as well call a spate a spate.
How about on arm64 we test for kali-arm64 and fall back to kali-armhf if not found to allow for a new app with a legacy application?

**Comment by kimocoder** [comment]
I think so, instead of armhf yes. Sounds good!
using adb install would be a primitive solution anyway

**Comment by kimocoder** [comment]
@Re4son is there anywhere we could communicate? telegram elsn?

**Comment by Re4son** [comment]
How come?

**Comment by kimocoder** [comment]
I have to walk through this again, closed but not forgotten 🙂 I had some questions, but I figured it out :+1:

**Comment by Re4son** [comment]
I'm back on telegram now as @re4son if you want to chat

**Pull request closed without merging**
