### PR TITLE
Adds REPEAT, DEFAULT_DELAY

### PR DESCRIPTION
**Pull request by TheNain38**
It also correct some other bugs. There shouldn't be any bugs left.
I tested it, I've seen no regression
@binkybear, @jmingov

### CODE REVIEW

**Comment by binkybear** [comment]
Looks good let me test first.

**Comment by binkybear** [comment]
Confirmed working, looks great!  Thanks for the good pr.

**Comment by TheNain38** [comment]
I like duckyscript, so I like making it better ^^

**Comment by TheNain38** [comment]
And you can even change the `DEFAULT_DELAY` in the middle of the code ^^

**Comment by TheNain38** [comment]
Maybe you should update nethunter.apk in kali-nethunter repo?

**Pull request merged**
