### PR TITLE
HID fixes

### PR DESCRIPTION
**Pull request by thedroidgeek**
* Fixed broken Enter key in findinlist()
* Added locale independent UAC prompt validation (original commit by aeMAETH.2501)
* Fixed Windows 10 HID attack
* Improved HID attack sleeps

### CODE REVIEW

**Comment by thedroidgeek** [comment]
Everything was tested.
Btw fyi the Windows 7 HID attack works for Windows 10 too.

**Comment by binkybear** [comment]
Testing shows no problems with HID.  Will wait for feedback from @jmingov .

**Comment by thedroidgeek** [comment]
The diff view doesn't make the changes very clear to see.
Well, there was a missing Enter keystroke just after the powershell line shows in the command prompt when I tried running the HID attack.
Using `print '''echo enter | hid-keyboard /dev/hidg0 keyboard'''` instead of `os.system('echo enter | /system/xbin/hid-keyboard /dev/hidg0 keyboard\n')` in findinlist() of keyseed.py seemed to fix it for me.
For the Windows 10 issue, it was the use of the right click mouse button (which will click on whatever the cursor is hovering at) instead of using the actual keyboard menu key.

**Comment by jmingov** [comment]
:+1:

**Pull request merged**
