### PR TITLE
SearchSploit Not Working After Update fix

### PR DESCRIPTION
**Pull request by Re4son**
Merge commit after testing in branch 2019.2-dev.
SearchSploit is working after the change without adverse effects.
Screenshot_20190331-113134_NetHunter

New apk that includes this fix published as v2019.2-rc2:
[https://github.com/offensive-security/nethunter-app/releases/tag/v2019.2-rc2](https://github.com/offensive-security/nethunter-app/releases/tag/v2019.2-rc2)

Please test thoroughly 
Issue #181

### CODE REVIEW

**Comment by kimocoder** [comment]
@Re4son finished up? I'm back online this evenening

**Comment by Re4son** [comment]
Looking good on my end but I haven't tested loading kernel modules with the new mounts. Do you have a kernel you can use to test tonight?

**Comment by kimocoder** [comment]
Yes, Im on it.. setting up a NUC build computer now!

**Comment by Re4son** [comment]
Hey @kimocoder - how attached are you to the "Press enter to continue" thing in the kali terminal?
How about a compromise: Do the prompt when a file /sdcard/nh_files/debug" exists and don't if it doesn't?

**Comment by Re4son** [comment]
@kimocoder - does the home screen display your kernel version in later versions, e.g 2019.2-rc4 and up?

**Pull request merged**
