### PR TITLE
Misc Updates

### PR DESCRIPTION
**Pull request by thehappydinoa**
- Updated gradle to the stable version
- Added all menu items to `strings.xml`
- Optimized imports
- Disabled app updates as it is not maintained and the plugin is broken
- Refactored `new Runnable()`
- Removed redundant type changes

Test Build: [nethunter-app-eae2b1a.apk](https://www.androidfilehost.com/?fid=11410963190603915206)

### CODE REVIEW

**Comment by thehappydinoa** [comment]
@Re4son I think I am good for now. Would you possibly be able to review my PR?

**Comment by Re4son** [comment]
Working on it

**Comment by kimocoder** [comment]
There are some conflicts that should be resolved here..

**Comment by thehappydinoa** [comment]
Thank you for resolving the conflict

**Pull request merged**
