### PR TITLE
Added dict_fr_bin

### PR DESCRIPTION
**Pull request by TheNain38**
It just has one bug, It needs a `space` command after these: `\x60` and `\x7e`. And I don't know how to add it.

### CODE REVIEW

**Comment by TheNain38** [comment]
Wait before merging, I made a mistake on '<' and '>'  since they aren't in the us keyboard

**Comment by TheNain38** [comment]
The characters '<' and '>' can't be outputed without echoing hex

**Comment by jmingov** [comment]
Looks good, ill wait for @binkybear  to take a look, he will merge the pull request if everything is fine.

Good job.

Ty!

**Comment by binkybear** [comment]
Looks good I will add a little something to duckhunter.py to read from there instead of dict_fr.

**Comment by TheNain38** [comment]
@binkybear I will also enhance duckhunter.py after your changes :) I'm also a C and python programmer.

**Comment by binkybear** [comment]
@TheNain38 - Great! I just pushed and tested.  Feel free to submit any enhancements or fixes.

**Comment by TheNain38** [comment]
You need to echo hex for characters '<' and '>'. And you also need to add a 'space' command after '`' and '~' to fix bugs it introduce

**Pull request merged**
