### PR TITLE
Fix MacChanger on OPO

### PR DESCRIPTION
**Pull request by m0rv4i**
Only Reset MAC was working without manually togging airplane mode for me on my OPO, but it all works fine for me now with these changes.

### CODE REVIEW

**Comment by m0rv4i** [comment]
Tested on my OPO/Android 6.0.1/CM version 13.1.2-ZNH2KAS3P0-bacon with Nethunter 3.15.2

**Comment by binkybear** [comment]
I'll give it a test tomorrow but it looks good.

**Comment by m0rv4i** [comment]
Manage to find time to give it a test @binkybear?

**Comment by binkybear** [comment]
Tested today and working without issues.  Thanks!

**Pull request merged**
