### PR TITLE
Correct syntax

### PR DESCRIPTION
**Pull request by TheNain38**
@binkybear I don't think this syntax is valid... If it was, then close this PR

### CODE REVIEW

**Comment by binkybear** [comment]
You are correct in changing the syntax.

**Comment by TheNain38** [comment]
I've done too much lua these times... ;)

**Comment by TheNain38** [comment]
@binkybear Actually, does it work now? Could you test it? (I don't have the time to setup a build environement on my machine right now). Or you could give me the latest nethunter.apk builded with my commits?

**Comment by binkybear** [comment]
@TheNain38 : Issue

root@kali:/sdcard/nh_files/modules# python duckhunter.py 
Traceback (most recent call last):
  File "duckhunter.py", line 8, in <module>
    from keyseed import *
  File "/sdcard/nh_files/modules/keyseed.py", line 1609
    else : print '''echo -ne "''' +dicts[locale][byte]+ '''" > /dev/hidg0'''
    ^
IndentationError: unexpected indent

**Comment by TheNain38** [comment]
#103

**Comment by binkybear** [comment]
Testing output in english:

Hello world!
Example of typing to computer. Nethunter is awesome!
I slept for 5 seconds, now I'm awake!
abcdefghijklmnopqrstuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ
1234567890-=!@#$%^&*()_+
[]\;',./{}|:"<>?`~

**Comment by binkybear** [comment]
APK file: https://transfer.sh/P85oD/nethunter-app-release.apk

**Comment by TheNain38** [comment]
thanks!

**Comment by TheNain38** [comment]
Testing output in french:

Hello world!
Example of typing to computer. Nethunter is awesome!
I slept for 5 seconds, now I'm awake!
abcdefghijklmnopqrstuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ
1234567890-=!@#$%^&*()_+
[]\;',./{}|:"<>?`~

**Comment by TheNain38** [comment]
If I set output to french, but using a us keyboard it gives me that:

````
Hello zorld/
Exq;ple of typing to co;puter< Nethunter is qzeso;e/
I slept for % secondsm noz I4; qzqke/
qbcdefghijkl;noparstuvzxyw
QBCDEFGHIJKL:NOPARSTUVZXYW
!@#$%^&*()6=/]"1\5-8+
,4m<>.3\|M

````

Same, but this time with a french keyboard and english output:

````
Hello zorld1
Exq,ple of typing to co,puter: Nethunter is qzeso,e1
I slept for ( seconds; noz Iù, qzqke1
qbcdefghijkl,noparstuvzxyw
QBCDEFGHIJKL?NOPARSTUVZXYW
&é"'(-è_çà)=1234567890°+
^$*mù;:!¨£µM%./§²

````

**Pull request merged**
