### PR TITLE
2019.2 dev

### PR DESCRIPTION
**Pull request by kimocoder**
@flypatriot fixed SearchSploit and other fixes.

But these fixes needs to be applied in the 2019.2-dev branch.
I did that here, so I may continue my work on our boot scripts and mount fixes.

@flypatriot awesome fix, but you need to have to delete and fork the project again to ensure you have the other branches we're using.

At last, great work. Glad to have you aboard sir! :1st_place_medal:

### CODE REVIEW

**Comment by kimocoder** [comment]
@Re4son this needs it's place in the 2019.2-dev branch and I cannot continue before it has been merged to I got a clean base to work with

**Comment by kimocoder** [comment]
Pull this to 2019.2-dev and I'll start working on my general fixes :+1:

**Comment by kimocoder** [comment]
@Re4son We've got 5 build/compile issues here.

mainly...

"synthesized for lambda desugaring: Type `com.google.common.collect.Multiset$-CC` was not found, it is required for default or static interface methods desugaring of `void com.google.common.collect.-$$Lambda$Multiset$yTxkVZMQHaYOoZD4ry_up4hmmvA.accept(java.lang.Object)`"

**Comment by flypatriot** [comment]
@kimocoder Thank's for your comment. I'll fork the project today. And great thank's for your job.

**Pull request merged**
