### PR TITLE
A mishmash of small updates that may or may not work.

### PR DESCRIPTION
**Pull request by fat-tire**
Just wanted to bring this a little up to date.  I don't have a device running API 27 or P... and the emulator needs root to test this which I also haven't set up.  So not sure if the notification channel part will work, but I think it should (?)  If not, fix it :)  I may have broken everything here.

I built w/Android Studio 3.2 Canary 12.

### CODE REVIEW

**Comment by fat-tire** [comment]
Just noticed #180 which may be better.  Maybe @aeroroland can take a look and integrate any build updates into his version or whatever and then everything will be great.  Cheers.

**Comment by jmingov** [comment]
:) Lets see if @aeroroland appears. Ty @fat-tire, nice to see you!

**Comment by aeroroland** [comment]
Second tag is the charm. I'll take a look and let you know within the next few days.

**Comment by fat-tire** [comment]
Sounds good :)  hey @jmingov !

**Comment by aeroroland** [comment]
@fat-tire, @jmingov, I finally got around to taking a look at the code online, and it looks like something I can merge in. I need to play with how to do that with git, and may be another week or so.

**Pull request merged**
