### PR TITLE
Add F11...F24

### PR DESCRIPTION
**Pull request by TheNain38**
It is supported in hid-keyboard

### CODE REVIEW

**Comment by TheNain38** [comment]
Wait don't merge this yet

**Comment by TheNain38** [comment]
Also, what is 'menu' in https://github.com/pelya/android-keyboard-gadget/blob/master/hid-gadget-test/jni/hid-gadget-test.c#L163 ?

**Comment by binkybear** [comment]
@TheNain38 - I assume the menu key is for special keyboards: https://en.wikipedia.org/wiki/Menu_key

**Comment by TheNain38** [comment]
Is it better to have menu instead of SHIFT f10?

**Comment by TheNain38** [comment]
And the 'volume-up' and 'volume-down' can't be used I suppose, since the USB descriptor is not the same?

**Comment by binkybear** [comment]
For menu key I would say it would be more convenient to just use menu instead of passing SHIFT f10 but either one should work so I guess it comes to personal choice and testing.

I think volume up/down is specific to keyboards with those keys so it may not be useful

**Comment by TheNain38** [comment]
And 'copy', 'cut', 'paste' ?

**Comment by TheNain38** [comment]
I think we should just merge this like that. There is nothing more that works for me

**Comment by TheNain38** [comment]
This is the last thing that is needed to have the fourth checkbox on #107?

**Comment by binkybear** [comment]
Yes, the should cover all other keyboard keys.  I do not have Windows 10 so a Windows10 cmd would be hard for me to test.

**Comment by TheNain38** [comment]
I have a Windows 7, Windows 8.1 and Windows 10 computer available ^^

**Comment by TheNain38** [comment]
Also, WIN8CMD should use the correct keyboard layout that was set. I'm going to add that for all WINxCMD

**Comment by TheNain38** [comment]
Or maybe all WINxCMD should translate to DuckyScript code?

**Comment by TheNain38** [comment]
@binkybear What is this command ? https://github.com/offensive-security/nethunter-app/blob/1b2811f5dca4e04e4e4db3476d4518026a9db2fb/assets/nh_files/modules/duckhunter.py#L190

**Comment by TheNain38** [comment]
I've done a WINCMD which gets Admin rights with any Windows and any keyboard layout, how do I name it? 'WINCMDUAC' or 'WINCMDADMIN' ?

**Pull request merged**
