### PR TITLE
2019.2 dev

### PR DESCRIPTION
**Pull request by kimocoder**
Here you got some all over fixes @Re4son 
Please do a walkthrough before merging and also, test if SearchSploit now works :+1:

### CODE REVIEW

**Comment by kimocoder** [comment]
Don't merge before it is properly tested, need some more time finishing up too

**Comment by kimocoder** [comment]
Note-to-self..

* Finish up removing hardcoding

**Comment by kimocoder** [comment]
* Finish up removing hardcoding

Then do proper testing and debug with Android Studio for some days
Also saw possibilities to complete some unfinished "TODO" in deauth fragment, but that May be later on.

**Comment by kimocoder** [comment]
another note-to-self, remember to test wifite2 as a issue report over there had some NetHunter issues with Lines/screen fucksize

**Comment by nik012003** [comment]
@kimocoder that TODO Is actually done but I discovered some other bugs in the deAuth code.
Will work on that as soon as I can.

**Comment by Re4son** [comment]
TODO: Nougat and up doesn't allow to install user apps in recovery so how about this:
- We'll install the nethunter app as system app (I'm working on that) via the installer
- The installer will query the Android OS version and if
   1. OS <= 7 then install apk's as user apps
   2. OS >= 8 than copy apks to data/data/com.offsec.nethunter/app_cache

The inititial run of the nethunter app should pm install each apk in data/data/com.offsec.nethunter/app_cache - I don't think we have to check whether it is installed already because it just won't install with error code "INSTALL_FAILED_ALREADY_EXISTS"

What do you think?

**Comment by kimocoder** [comment]
Sounds good, would have been awesome to check that off the list too.
I'll wrap up the hardcoding leftover this evening and start debug the app :+1:

**Comment by Re4son** [comment]
Ready for me to review and test @kimocoder ?

**Comment by kimocoder** [comment]
@Re4son there was too much problems introduced with this, I have to make a totall re-work to make sure the issues doesn't persist. But the SearchSploit fix in the other PR is interessant, If that fixed that issue, I got some other fixes to include. Closng for now, but will re-write my PR shortly

**Pull request closed without merging**
