### PR TITLE
Several fixes. See description.

### PR DESCRIPTION
**Pull request by kimocoder**
* SearchSploit fixes, also removed a issue with the "port" setting with it, so better remove it.
* Add support for /dev/shm
* Improved both "bootkali", "bootkali_init" and "killkali" script

There are still some work to do. I'll remove the hardcode in few hours and then I'll go through.

### CODE REVIEW

**Comment by kimocoder** [comment]
This is finished, complete the others later.
Needs to be reviewed

**Comment by Re4son** [comment]
Done some changes to assets/scripts/bootkali_init at the same time to mount /system. Would you mind having a look at the conflicts?

**Comment by kimocoder** [comment]
Smashed some, but please review.. actually never had any conflicts before.

There is a comment at "#$busybox mount -r -o bind /system/lib/modules $mnt/lib/modules"
You don't want the modules binded ?

**Comment by Re4son** [comment]
We need the modules under /lib/modules to run modprobe in the chroot

**Comment by kimocoder** [comment]
I actually encountering problems with not finding busybox, just updated the app... but building from build.py now

**Comment by Re4son** [comment]
Give me an hour or two to remove some conflicts

**Comment by Re4son** [comment]
I've done some changes, mainly removing duplicates.
Can you do a final check please before I merge?

**Pull request merged**
